//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.Pinz.Client.RemoteServiceConsumer.PinzAdminServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompanyDO", Namespace="http://schemas.datacontract.org/2004/07/Com.Pinz.Server.DataAccess.Model")]
    [System.SerializableAttribute()]
    public partial class CompanyDO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CompanyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CompanyId {
            get {
                return this.CompanyIdField;
            }
            set {
                if ((this.CompanyIdField.Equals(value) != true)) {
                    this.CompanyIdField = value;
                    this.RaisePropertyChanged("CompanyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PinzAdminServiceReference.IPinzAdminService")]
    public interface IPinzAdminService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPinzAdminService/CreateCompany", ReplyAction="http://tempuri.org/IPinzAdminService/CreateCompanyResponse")]
        Com.Pinz.Client.RemoteServiceConsumer.PinzAdminServiceReference.CompanyDO CreateCompany(Com.Pinz.Client.RemoteServiceConsumer.PinzAdminServiceReference.CompanyDO company);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPinzAdminService/CreateCompany", ReplyAction="http://tempuri.org/IPinzAdminService/CreateCompanyResponse")]
        System.Threading.Tasks.Task<Com.Pinz.Client.RemoteServiceConsumer.PinzAdminServiceReference.CompanyDO> CreateCompanyAsync(Com.Pinz.Client.RemoteServiceConsumer.PinzAdminServiceReference.CompanyDO company);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPinzAdminService/UpdateCompany", ReplyAction="http://tempuri.org/IPinzAdminService/UpdateCompanyResponse")]
        Com.Pinz.Client.RemoteServiceConsumer.PinzAdminServiceReference.CompanyDO UpdateCompany(Com.Pinz.Client.RemoteServiceConsumer.PinzAdminServiceReference.CompanyDO company);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPinzAdminService/UpdateCompany", ReplyAction="http://tempuri.org/IPinzAdminService/UpdateCompanyResponse")]
        System.Threading.Tasks.Task<Com.Pinz.Client.RemoteServiceConsumer.PinzAdminServiceReference.CompanyDO> UpdateCompanyAsync(Com.Pinz.Client.RemoteServiceConsumer.PinzAdminServiceReference.CompanyDO company);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPinzAdminService/DeleteCompany", ReplyAction="http://tempuri.org/IPinzAdminService/DeleteCompanyResponse")]
        void DeleteCompany(Com.Pinz.Client.RemoteServiceConsumer.PinzAdminServiceReference.CompanyDO company);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPinzAdminService/DeleteCompany", ReplyAction="http://tempuri.org/IPinzAdminService/DeleteCompanyResponse")]
        System.Threading.Tasks.Task DeleteCompanyAsync(Com.Pinz.Client.RemoteServiceConsumer.PinzAdminServiceReference.CompanyDO company);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPinzAdminServiceChannel : Com.Pinz.Client.RemoteServiceConsumer.PinzAdminServiceReference.IPinzAdminService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PinzAdminServiceClient : System.ServiceModel.ClientBase<Com.Pinz.Client.RemoteServiceConsumer.PinzAdminServiceReference.IPinzAdminService>, Com.Pinz.Client.RemoteServiceConsumer.PinzAdminServiceReference.IPinzAdminService {
        
        public PinzAdminServiceClient() {
        }
        
        public PinzAdminServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PinzAdminServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PinzAdminServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PinzAdminServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Com.Pinz.Client.RemoteServiceConsumer.PinzAdminServiceReference.CompanyDO CreateCompany(Com.Pinz.Client.RemoteServiceConsumer.PinzAdminServiceReference.CompanyDO company) {
            return base.Channel.CreateCompany(company);
        }
        
        public System.Threading.Tasks.Task<Com.Pinz.Client.RemoteServiceConsumer.PinzAdminServiceReference.CompanyDO> CreateCompanyAsync(Com.Pinz.Client.RemoteServiceConsumer.PinzAdminServiceReference.CompanyDO company) {
            return base.Channel.CreateCompanyAsync(company);
        }
        
        public Com.Pinz.Client.RemoteServiceConsumer.PinzAdminServiceReference.CompanyDO UpdateCompany(Com.Pinz.Client.RemoteServiceConsumer.PinzAdminServiceReference.CompanyDO company) {
            return base.Channel.UpdateCompany(company);
        }
        
        public System.Threading.Tasks.Task<Com.Pinz.Client.RemoteServiceConsumer.PinzAdminServiceReference.CompanyDO> UpdateCompanyAsync(Com.Pinz.Client.RemoteServiceConsumer.PinzAdminServiceReference.CompanyDO company) {
            return base.Channel.UpdateCompanyAsync(company);
        }
        
        public void DeleteCompany(Com.Pinz.Client.RemoteServiceConsumer.PinzAdminServiceReference.CompanyDO company) {
            base.Channel.DeleteCompany(company);
        }
        
        public System.Threading.Tasks.Task DeleteCompanyAsync(Com.Pinz.Client.RemoteServiceConsumer.PinzAdminServiceReference.CompanyDO company) {
            return base.Channel.DeleteCompanyAsync(company);
        }
    }
}
